import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Container, Col, Card, Row } from 'react-bootstrap'
import { fetchAvailableArticles } from '../utils/requests';

function Home({ availableArticles }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          {availableArticles.map((article) => (
            <Col xs={4} key={article.uuid} className="d-flex">
              <Card>
                <Link href={`/article/${article.uuid}`}>
                  <a className="article">
                    <div className="article-extra-details">
                      <div className="article-tags">
                        {article.field_tags_export.slice(0, 3).map((tag) => (
                          <div className="article-tag" key={tag}>{tag}</div>
                        ))}
                      </div>
                      <div className="article-date">
                        {new Date(article.created).toDateString()}
                      </div>
                    </div>
                    <div className="article-img">
                      <Image src={`http://drupal.localhost:8000/${article.field_image}`} layout="fill" />
                    </div>
                    <h4 className="article-title">{article.title}</h4>
                    <div className="article-body" dangerouslySetInnerHTML={{ __html: article.body }} />
                  </a>
                </Link>
              </Card>
            </Col>
          ))}
        </Row>
      </Container>
    </>
  )
}

export async function getServerSideProps(context) {
  const availableArticles = await fetchAvailableArticles();

  return {
    props: {
      availableArticles: availableArticles
    }
  }
}

export default Home;